import registerComponent from 'core/registerComponent';
import Layout from 'components/Layout/Layout';
import Button from 'components/Button/Button';
import ChatList from 'components/ChatList/ChatList';
import ChatView from 'components/ChatView/ChatView';
import ChatPreview from 'components/ChatPreview/ChatPreview';
import Chat from 'components/Chat/Chat';
import Input from 'components/Input/Input';
import Message from 'components/Message/Message';
import MessagePreview from 'components/MessagePreview/MessagePreview';
import Sidebar from 'components/Sidebar/Sidebar';
import ChooseChat from 'pages/ChooseChat/ChooseChat';
import MainChat from 'pages/MainChat/MainChat';
import Link from 'components/Link/Link';
import Form from 'components/Form/Form';
import Field from 'components/Field/Field';
import InputError from 'components/InputError/InputError';
import Table from '../components/Table/Table';
import Img from '../components/Img/Img';
import Subtitle from '../components/Subtitle/Subtitle';
import PageTitle from '../components/PageTitle/PageTitle';
import ProfileIcon from '../components/ProfileIcon/ProfileIcon';
import SidebarReturn from '../components/SidebarReturn/SidebarReturn';

registerComponent(Layout);
registerComponent(Button);
registerComponent(Link);
registerComponent(ChatList);
registerComponent(ChatView);
registerComponent(Chat);
registerComponent(ChatPreview);
registerComponent(Input);
registerComponent(MessagePreview);
registerComponent(Message);
registerComponent(Sidebar);
registerComponent(ChooseChat);
registerComponent(MainChat);
registerComponent(Form);
registerComponent(Field);
registerComponent(Link);
registerComponent(InputError);
registerComponent(Table);
registerComponent(Img);
registerComponent(Subtitle);
registerComponent(PageTitle);
registerComponent(ProfileIcon);
registerComponent(SidebarReturn);
